name: Swift # Will also be the name of the build badge

on:
  push:
    branches: [ master ]

jobs:
  create_code_coverage_badge:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test --enable-code-coverage

    - name: Code Coverage
      uses: maxep/spm-lcov-action@0.3.1
      with:
        output-file: coverage.json
        file-format: text

    - name: Extract Coverage Percentage
      id: coverage_step
      # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-output-parameter
      run: echo "::set-output name=coverage::$(cat coverage.json | jq -r ".data[0].totals.lines.percent" | head -c 5)"

    - name: Create Status Badge
      uses: emibcn/badge-action@v1
      with:
        label: 'Code Coverage'
        status: ${{ steps.coverage_step.outputs.coverage }}%
        color: 'orange' #'green'
        path: '.github/badges/coverage.svg'

    - name: Push Back Status Badge
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        branch: master
        file_pattern: ".github/badges"
        commit_message: "CI: Updated Swift documentation + Code Coverage badge"
        commit_user_name: "GitHub Action"
        commit_user_email: "action@github.com"
        push_options: --force
