name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #run_unit_tests:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Run tests
  #    run: swift test -v
  
  publish_jazzy_docs:
    runs-on: macos-latest
    steps:
      - name: Publish Jazzy Docs
        # You may pin to the exact commit or the version.
        # uses: Steven0351/publish-jazzy-docs@9ac83856c845f4b7d4803f1ebb3bbc2fa85bbfdd
        uses: Steven0351/publish-jazzy-docs@v1.1.2
        with:
          # Path to .jazzy.yml file - preferred
          #config: # optional
          # Arguments to pass to Jazzy
          args: "--clean --module Disruptive --swift-build-tool spm --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5"
          # Jazzy Version
          #version: # optional
          # Personal access token
          personal_access_token: ${{ secrets.GITHUB_TOKEN }}
  
  #publish_jazzy_docs:
  #  runs-on: macos-latest
  #  steps:
  #    - uses: actions/checkout@v2
  #    - name: Generate Jazzy Docs
  #      uses: sersoft-gmbh/swifty-docs-action@v1
  #      with:
  #        output: jazzy-docs
  #    - name: Publish Jazzy Docs
  #      run: git commit -am "Updated Jazzy Docs" && git push
      
  
  #publish_jazzy_docs:
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Generate Jazzy Docs
  #    run: jazzy \
  #         --clean
  #         --module Disruptive \
  #         --swift-build-tool spm \
  #         --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5 \
  #         --output docs
  #  - name: Public Jazzy Docs
  #    run: git commit -am "Updated Jazzy Docs" && \
  #         git push
      
